# Generated by Django 5.0.7 on 2024-07-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoverse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='media/{user_id}/'),
        ),
    ]
