# Generated by Django 5.0.7 on 2024-07-21 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_name', models.CharField(choices=[('UPLOAD_SIZE_LIMIT', 'upload_size_limit'), ('UPLOAD_NUMBER_LIMIT', 'upload_number_limit'), ('STORAGE_QUOTA', 'storage_quota'), ('DAILY_UPLOAD_LIMIT', 'daily_upload_limit'), ('MONTHLY_UPLOAD_LIMIT', 'monthly_upload_limit'), ('CONCURRENT_UPLOADS_LIMIT', 'concurrent_uploads_limit')], max_length=50)),
                ('limit_value', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
