# Generated by Django 5.0.7 on 2024-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlimit',
            name='unit',
            field=models.CharField(choices=[('KB', 'KB'), ('MB', 'MB'), ('GB', 'GB'), ('NUMBER', 'NUMBER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userlimit',
            name='limit_value',
            field=models.PositiveIntegerField(help_text='Enter the limit value. Units:<br>- upload_size_limit: mb<br>- upload_number_limit: number of uploads<br>- storage_quota: mb<br>- daily_upload_limit: number of uploads<br>- monthly_upload_limit: number of uploads<br>- concurrent_uploads_limit: number of concurrent uploads'),
        ),
    ]
